// <auto-generated />
using System;
using BowlingSecretary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BowlingSecretary.Migrations
{
    [DbContext(typeof(BowlingSecretaryContext))]
    [Migration("20181107195241_Teams")]
    partial class Teams
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BowlingSecretary.Models.League", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BowlersPerTeam");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfLanes");

                    b.Property<int>("PositionRounds");

                    b.HasKey("ID");

                    b.ToTable("League");
                });

            modelBuilder.Entity("BowlingSecretary.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LeagueID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("LeagueID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("BowlingSecretary.Models.Team", b =>
                {
                    b.HasOne("BowlingSecretary.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueID");
                });
#pragma warning restore 612, 618
        }
    }
}
